---
- name: get default runlevel
  command: systemctl get-default
  register: runlevel

- name: sets graphical target
  command: systemctl set-default graphical.target
  when:
    - target == 'graphical'
    - runlevel.stdout != "graphical.target"

- name: sets multi-user target
  command: systemctl set-default multi-user.target
  when:
    - target == 'text'
    - runlevel.stdout != "multi-user.target"
