---
- name: install calamares package
  zypper: name=calamares-branding-zigzag state='{{live_additions}}'

- name: add liveuser user
  user: name=liveuser groups=wheel uid=2000 state='{{live_additions}}'

- name: disable sudo password prompt for liveuser
  lineinfile:
    path: /etc/sudoers
    line: 'liveuser ALL=(ALL) NOPASSWD:ALL'
    owner: root
    group: root
    mode: 0400
    state: '{{live_additions}}'
