---
- name: set sudo as authentication method for kdesu
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kdesurc
    section: super-user-command
    option: super-user-command
    value: sudo

- name: use double-click across the interface
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kdeglobals
    section: KDE
    option: SingleClick
    value: false

- name: change default interface fonts
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kdeglobals
    section: General
    option: '{{item.option}}'
    value: '{{item.value}}'
  with_items:
  - { option: 'fixed', value: 'Iosevka Term,14,-1,5,50,0,0,0,0,0,Regular'}
  - { option: 'font', value: 'Noto Sans,10,-1,5,50,0,0,0,0,0,Regular'}
  - { option: 'menuFont', value: 'Noto Sans,10,-1,5,50,0,0,0,0,0,Regular'}
  - { option: 'smallestReadableFont', value: 'Noto Sans,10,-1,5,50,0,0,0,0,0,Regular'}
  - { option: 'toolBarFont', value: 'Noto Sans,10,-1,5,50,0,0,0,0,0,Regular'}

- name: change default window manager font
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kdeglobals
    section: WM
    option: activeFont
    value: 'Noto Sans,10,-1,5,50,0,0,0,0,0,Regular'

- name: disable plasma tooltips
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/plasmarc
    section: PlasmaToolTips
    option: Delay
    value: -1

- name: reduce bouncing coursor timeout
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/klaunchrc
    section: BusyCursorSettings
    option: Timeout
    value: 1

- name: always start with fresh session
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/ksmserverrc
    section: General
    option: loginMode
    value: default

- name: only allow dragging windows by titlebars
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/breezerc
    section: Style
    option: WindowDragMode
    value: WD_NONE

- name: disable baloo search engine
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/baloofilerc
    section: Basic Settings
    option: Indexing-Enabled
    value: false

- name: use common properties for all directories
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/dolphinrc
    section: General
    option: GlobalViewProps
    value: true

- name: disable some of krunner plugins
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/krunnerrc
    section: Plugins
    option: '{{item}}'
    value: false
  with_items:
  - appstreamrunnerEnabled
  - bookmarksEnabled
  - kwinEnabled
  - locationsEnabled
  - org.kde.activitiesEnabled
  - org.kde.windowedwidgetsEnabled
  - placesEnabled
  - plasma-desktopEnabled
  - recentdocumentsEnabled
  - shellEnabled
  - webshortcutsEnabled

- name: enable natural scrolling
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/touchpadrc
    section: parameters
    option: InvertVertScroll
    value: true

- name: set keyboard repeat delay value
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kcminputrc
    section: Keyboard
    option: RepeatDelay
    value: 500

- name: set keyboard repeat rate value
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kcminputrc
    section: Keyboard
    option: RepeatRate
    value: 30

- name: show tabs in konsole only when needed
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/konsolerc
    section: TabBar
    option: TabBarVisibility
    value: ShowTabBarWhenNeeded
