---
- name: disable window side borders
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: org.kde.kdecoration2
    option: BorderSize
    value: NoSides

- name: set toolbar controls (left)
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: org.kde.kdecoration2
    option: ButtonsOnLeft
    value: ''

- name: set toolbar controls (right)
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: org.kde.kdecoration2
    option: ButtonsOnRight
    value: IAX

- name: disable top-left hot corner action
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: Effect-PresentWindows
    option: BorderActivateAll
    value: 9

- name: set up 4 virtual desktops
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: Desktops
    option: Number
    value: 4

- name: set animation speed to fast
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: Compositing
    option: AnimationSpeed
    value: 1

- name: disable active window highlight on alt-tab
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: TabBox
    option: HighlightWindows
    value: false

- name: disable redundant kwin effects
  ini_file:
    no_extra_spaces: yes
    path: /etc/skel/.config/kwinrc
    section: Plugins
    option: '{{item}}'
    value: false
  with_items:
  - kwin4_effect_translucencyEnabled
  - kwin4_effect_maximizeEnabled
  - minimizeanimationEnabled
  - slidingpopupsEnabled
