---
- name: install plasma pattern
  zypper: name=patterns-zigzag-plasma state=present

- name: install desktop applications
  zypper: name={{item}} state=present
  with_items:
  - chromium
  - dolphin
  - konsole
  - kwrite
  - kcalc
  - partitionmanager
  - kolourpaint
  - kcolorchooser
  - okular
  - ark
  - gwenview
  - transmission-qt
  - ksysguard5
  - discover
  - kwalletmanager5
  - spectacle
  - filelight
  - keepassxc
  - mpv
  - youtube-dl

- name: install kde-connect
  zypper: name=kdeconnect-kde state=present
