---
- name: install desktop apps
  zypper:
    name:
      - chromium
      - dolphin
      - konsole
      - kwrite
      - kcalc
      - partitionmanager
      - kolourpaint
      - kcolorchooser
      - okular
      - ark
      - gwenview
      - transmission-qt
      - ksysguard5
      - discover
      - kwalletmanager5
      - spectacle
      - filelight
      - keepassxc
      - vlc-qt
      - youtube-dl
    state: present

# Starting from Leap 15.1 discover backends have been split
- name: install additional discover backends
  zypper:
    name:
      - discover-backend-packagekit
      - discover-backend-flatpak
    state: present
  when: is_version_gte_151 == true

# Only Tumbleweed has fwupd backend
- name: install additional discover backends
  zypper: name=discover-backend-fwupd state=present
  when: is_tumbleweed == true
