---
- name: install x.org and utils
  zypper: name={{item}} state=present
  with_items:
    - patterns-zigzag-xfirmware
    - xorg-x11-essentials
    - xorg-x11-server
    - xorg-x11-fonts
    - xorg-x11-driver-video
    - xf86-input-libinput
    - xrandr
    - xdpyinfo
    - xhost
    - xclip
    - Mesa-demo-x

# VirtualBox (kernel < 4.13 does not ship with vboxvideo module)
- name: install virtualbox module on leap
  zypper: name=virtualbox-guest-kmp-default state=present
  when: is_leap
