---
# openSUSE base version for the system
# valid options: leap, tumbleweed
base_version: 'tumbleweed'

# Include non-free packages
# valid options: true, false
non_free: true

# Enable testing repository
# valid options: true, false
testing_repo: false
