---
- name: install apparmor packages
  zypper: name={{item}} state=present
  with_items:
  - audit
  - apparmor-profiles
  - apparmor-parser

- name: enable apparmor service
  systemd: name=apparmor enabled=yes
