---
- import_tasks: packages/base.yml
- import_tasks: packages/x11.yml
- import_tasks: packages/plasma.yml
- import_tasks: packages/apps.yml
- import_tasks: packages/laptop.yml

- import_tasks: services.yml
