---
- name: install desktop base
  zypper: name={{item}} state=present
  with_items:
  - patterns-zigzag-graphical
  - patterns-zigzag-laptop
  - flatpak
  - xdg-user-dirs
  - xdg-utils
  - PackageKit-backend-zypp
  - PackageKit-gstreamer-plugin

- name: install audio stack
  zypper: name={{item}} state=present
  with_items:
  - alsa-firmware
  - alsa-utils
  - alsa-plugins-pulse
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pulseaudio-module-zeroconf
  - pulseaudio-module-x11

- name: install live medium tools
  zypper: name={{item}} state=present
  with_items:
  - calamares-branding-zigzag
  - zigzag-live-service

- name: enable zigzag-live service
  systemd: name=zigzag-live enabled=yes
