---
- name: install desktop base
  zypper: name={{item}} state=present
  with_items:
  - patterns-zigzag-graphical
  - flatpak
  - PackageKit-backend-zypp
  - PackageKit-gstreamer-plugin

- name: install audio stack
  zypper: name={{item}} state=present
  with_items:
  - alsa-firmware
  - alsa-utils
  - alsa-plugins-pulse
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pulseaudio-module-zeroconf
  - pulseaudio-module-x11

- import_tasks: networkmanager.yml
- import_tasks: laptop.yml
