---
# this package will be re-added at the later stage, it needs to be
# removed here so that it's dependencies are marked as manually
# installed if we list them in the playbook
- name: remove dracut-kiwi-live package
  zypper: name=dracut-kiwi-live state=absent

- name: install base packages
  zypper: name={{item}} state=present
  with_items:
    - patterns-base-minimal_base
    - patterns-zigzag-firmware
    - grub2-branding-openSUSE
    - grub2-i386-pc
    - grub2-x86_64-efi
    - syslinux
    - kernel-default
    - rng-tools
    - sudo
    - finger
    - timezone
    - man
    - psmisc
    - lsof
    - curl
    - less
    - tar
    - iproute2
    - iputils
    - ca-certificates-mozilla
    - mozilla-nss-certs
    - crda
    - audit
    - apparmor-profiles
    - apparmor-parser
    - avahi
    - zigzag-languages
