---
- hosts: all
  tasks:
    - name: install live medium tools
      zypper: name={{item}} state=present
      with_items:
        - calamares-branding-zigzag
        - dracut-kiwi-live
        - zigzag-live-service

    - name: enable zigzag-live service
      systemd: name=zigzag-live enabled=yes

    - name: refresh repositories to gather appstream data
      zypper_repository: name='*' runrefresh=yes
