---
- hosts: all
  tasks:
  - name: remove live medium tools
    zypper: name={{item}} state=absent
    with_items:
    - calamares-branding-zigzag
    - zigzag-live-service
    - dracut-kiwi-live

  - name: install translation packages
    command: zigzag-languages -y
    ignore_errors: yes
