---
- hosts: all
  tasks:
    - name: remove live medium tools
      zypper: name={{item}} state=absent
      with_items:
        - calamares-branding-zigzag
        - dracut-kiwi-live
        - zigzag-live-service

    # fix locale settings after installation (opensuse quirk)
    # copy language from /etc/locale.conf to /etc/sysconfig/language
    - name: set the language in /etc/sysconfig/language
      lineinfile:
        path: /etc/sysconfig/language
        regexp: '^RC_LANG'
        line: 'RC_LANG="{{ item }}"'
      with_items: "{{ lookup('ini', 'LANG type=properties file=/etc/locale.conf') }}"

    - name: install translation packages
      command: zigzag-languages -y
      ignore_errors: yes

    - name: enable translation periodic check
      systemd: name=zigzag-languages.timer enabled=yes
