---
- hosts: all
  pre_tasks:
    - import_role: name=kiwi_pre
      when: is_kiwi
  post_tasks:
    - import_role: name=kiwi_post
      when: is_kiwi
  roles:
    - base
    - sudo
    - samba
    - ioscheduler
    - desktop
    - polkit
    - fonts
