---
- hosts: all
  pre_tasks:
    - import_tasks: kiwi/pre_tasks.yml
      when: is_kiwi
  post_tasks:
    - import_tasks: kiwi/post_tasks.yml
      when: is_kiwi
  roles:
    - base
    - sudo
    - samba
    - ioscheduler
    - desktop
    - polkit
    - fonts
