---
- hosts: all
  roles:
  - base
  - sudo
  - rngd
  - apparmor
  - firewalld
  - ioscheduler
  - polkit
  - { role: non_free, when: non_free == true }
  - { role: plasma, when: target == 'graphical' }
