---
- hosts: all
  roles:
  - base
  - sudo
  - rngd
  - network
  - apparmor
  - firewalld
  - ioscheduler
  - polkit
  - extra
  - { role: plasma, when: target == 'graphical' }

  # live-image tasks should be performed at the end
  - { role: live-image, when: live_image | default(false) }
