---
- name: install font packages
  zypper: name={{item}} state=present
  with_items:
    - fonts-config
    - liberation-fonts
    - dejavu-fonts
    - iosevka-fonts
    - noto-sans-fonts
    - noto-sans-sc-fonts
    - noto-sans-jp-fonts
    - noto-coloremoji-fonts

- name: install microsoft fonts
  zypper: name=fetchmsttfonts state=present
  when: non_free == true

- name: copy font config
  template: src=fonts-config.j2 dest=/etc/sysconfig/fonts-config
  notify:
    - apply fonts-config
